### ISSUE TITLE
Poor quality triangles at boundary of two regions in mmgs

### ISSUE THREAD

**Issue by updega2** [MmgTools/mmg#10]
I am surface remeshing with mmgs, and I have two different regions. I prescribe two different mesh sizes for the two regions, and the boundary in between the two regions ends up with very poor quality triangles. The triangles at the boundary are also smaller than either of the prescribed sizes. Is this what I should expect or am I doing something wrong?

**Comment by Algiane** [comment]
Hello, 

I have seen that you have post your issue here and on the Mmg forum. You can use both (it is redirected to the same people). I will respond you on the forum. 

Thank you
