### ISSUE TITLE
[Linux] FindSCOTCH.cmake and FindElas.cmake outside of CMAKE_MODULE_PATH.

### ISSUE THREAD

**Issue by bartoszek** [MmgTools/mmg#109]
I'm having a smalish problem when building `elmerfem` with `mmg:5.5.2` on linux host.
Mainly `cmake` complains about missing `FindSCOTCH.cmake`.
`FindSCOTCH.cmake` gets installed into `/usr/lib/cmake/mmg` here:
https://github.com/MmgTools/mmg/blob/71e46c5ba0a2345aefb32e523aafef7f0e71126e/CMakeLists.txt#L485-L488
Instead of /usr/lib/cmake/Modules which allow `cmake` to discover it.
You could move the file, or append current dir to path like in for example `gnuradio` `GnuradioConfig.cmake` here:
```cmake
# Allows us to use all .cmake files in this directory
list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_LIST_DIR}")
```
https://github.com/gnuradio/gnuradio/blob/146e9f34c2e7e8b833c1747867e3275475d94be2/cmake/Modules/GnuradioConfig.cmake.in#L10-L11

**Comment by bartoszek** [comment]
@Algiane you've misunderstood me.
There's no problem with building `mmg` there's on the other hand an issue with building `cmake` projects that links to `mmg`.
You have to specify `CMAKE_MODULE_PATH` inside `mmgConfig.cmake`, other wise `find_package(mmg)` will fail in with missing `FindSCOTCH.cmake` error ( [check out cmake.patch in AUR/mmg PKGBUILD](https://aur.archlinux.org/packages/mmg/) )
https://github.com/MmgTools/mmg/blob/11ecca26ff09640a3eb5b6ae037aa9657a0ce0e9/cmake/config/mmgConfig.cmake.in#L1-L10

**Comment by Algiane** [comment]
Thanks for the explanation of the issue and it solution!
