### ISSUE TITLE
 MMGS_Set_meshSize function

### ISSUE THREAD

**Issue by edljk** [MmgTools/mmg#11]
I tried to call the llibmmgs.so without using a file mesh.
I obtained seg fault in calling the  MMGS_Set_meshSize function. I wonder if there is no problem in the memory allocation step : should  ``` mesh->nt```  be replaced   by ``` mesh->ntmax ``` ? And the line 
``` mesh->tetra[k].v[3] = k+1; ``` by ``` mesh->tria[k].v[2] = k+1;``` ?
By the way, it would be nice to have a complete example (like for the full 3D case) of calling llibmmgs.so without loading a file.

**Comment by Algiane** [comment]
Hello,

I think that this error has been patched some weeks ago. Maybe you need to update your repository.

Actually, we need to expand our libraries examples. I will add the complete example of calling the mmgs library without a loading file as soon as possible.

Regards, 

Algiane

**Comment by edljk** [comment]
Oups, you are right. I just updated my version and everything works like a charm.

**Comment by Algiane** [comment]
Ok, :-). I close the issue!
