### ISSUE TITLE
[Feature request] Custom isosurface boundary label

### ISSUE THREAD

**Issue by cbritopacheco** [MmgTools/mmg#118]
# Goal

I want to have a custom isosurface boundary label to avoid any possible reference conflicts. So for example, the following command ([from the doc](https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials/mmg-remesher-mmg2d/implicit-domain-meshing))
```
mmg2d_O3 multi-mat -ls
```
will produce a mesh where the zero level set has boundary label set to `MG_ISO` (which in the implementation is the number 10). I want to be able to change this label using the `MMG2D_Set_iparameter()` API function. I don't need a file frontend (ie. the parameter file) since my integration with MMG is using the library API.

# Possible solution

It should be sufficient to add a new field `int isoref` to `MMG5_Info` and replace all ocurrences of `MG_ISO` to something like `mesh->info.isoref`, since we always have the `mesh` pointer available.

**Comment by Algiane** [comment]
Hi, 

Thanks for this proposition and for the PR. I will at least add a continuous integration test case to check this, I will also try to keep consistency between the command line options and the API.

I am currently sick with covid (and with my small children at home) so very probably it will take 1 or 2 weeks before I have the time to look at this task.

Sorry for the delay,

Best Regards,
Algiane

**Comment by cbritopacheco** [comment]
Hi Algiane,
Thanks for your response and your work! If you need me to change something in the PR please feel free to review the changes :)

Until then!

**Comment by cbritopacheco** [comment]
The PR has been merged so I'm closing this issue :)
