### ISSUE TITLE
Using mmg for remeshing a tetrahedral 3D mesh

### ISSUE THREAD

**Issue by ttsesm** [MmgTools/mmg#133]
Hi @Algiane,

Ok, here is my actual problem.

I would like to use mmg for remeshing a tetrahedral 3D mesh. Currently I am using [vedo](https://github.com/marcomusy/vedo) and [pyvista_tetgen](https://github.com/pyvista/tetgen) in order tetrahedralize a 3D mesh and then fracture it in smaller pieces. However, the quality of the tetrahedra result from the `tetgen` lib is not that good. In principle I want to do something similar to this [blender addon](https://www.youtube.com/watch?v=ZG_ZMnKzVTQ). However the result so far as you can see from fractured pieces is not that realistic:
![anim-opt](https://user-images.githubusercontent.com/10189018/157677899-046b55dd-e16c-4526-8a97-c24263c3d247.gif)

The fractured parts are too rough due to the internal tetrahedra being too sparse???

Searching around how to optimize this I found about mmg and that it is possible to apply volume remeshing. Thus I was thinking to use the mmg lib to improve the tetrahedral meshing quality. Do you think I could make it work so that I can get a more refined ("realistic") output on the fractured sides?

Thanks.

**Comment by Algiane** [comment]
Hi,

I am not sure to understand entirely your process : are you free to improve the tetra mesh before the decomposition? If yes, I think that it is the thing to do and you can use Mmg. To control the boundary approximation you will have to use the `-hausd` option (you can look [here](http://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials/mmg-remesher-mmgs/mmg-remesher-smooth-surface-remeshing) for an example with Mmgs but the surface model and the options are the same than in Mmg3d).
You can use the `-hmax` option to control the maximal edge size (http://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials/mmg-remesher-mmgs/mmg-remesher-smooth-surface-remeshing).

If you want to decompose the mesh first, work will be more complicated to obtain something. Mmg can refine your internal interfaces but:
  -  if sharp angles detection is allowed, Mmg will have very few degrees of freedom to improve the mesh of interfaces. It will only split a little the surface without improving it globally;
   - if sharp angles detection is disabled (`-nr`), Mmg will construct a smooth surface from the splitted interfaces and will probably insert lot of nodes to be able to have a sufficiently good approximation of these spurious surfaces.
   
 Hope it helps.
 Best Regards,
 
 algiane

**Comment by ttsesm** [comment]
Yes initially my mesh is hollow, imagine that so you have the surface and inside is empty. Now I want to solidify the interior with tetrahedra so that when I apply the decomposition to get a surface on the sides that the decomposition is applied. However, I need these tetrahedra to be quite high density so that I can get finer details on fractured sides. 

The `-hausd` option will remesh only my interior tetrahedra or also the initial surface since I would like to maintain the initial boundaries and size of my mesh.

Thanks.

**Comment by Algiane** [comment]
Ok, so if I understand:
  - external bunny surface must be preserved (no modification of the discretization);
  - internal tetrahedralization and decomposition interfaces has to be refined (except along intersection of interface and external surface of course).
  
  Am I right?
  
  I have a last question on your process, do you:
    - decompose the surface, then generate the interior and after that decompose the interior?
    - decompose the surface, then directly generate a "decomposed" interior ?
    - generate the interior, then decompose both surface and interior?
    
    Thank by advance,
    Algiane

**Comment by ttsesm** [comment]
> Ok, so if I understand:
> 
>     * external bunny surface must be preserved (no modification of the discretization);
> 
>     * internal tetrahedralization and decomposition interfaces has to be refined (except along intersection of interface and external surface of course).
> 
> 
> Am I right?
> 
Yes that's correct.

> I have a last question on your process, do you: - decompose the surface, then generate the interior and after that decompose the interior? - decompose the surface, then directly generate a "decomposed" interior ? - generate the interior, then decompose both surface and interior?
> 
The last case, first I create the interior and then decompose both surface and interior. In practice now once I have the tetrahedra mesh I am creating some random seeds on the surface of the mesh and then by assigning to each tetrahedron the id of the closest seed point I get my clusters (i.e. pieces).

**Comment by Algiane** [comment]
Hi,
thanks for the feedback. As you are using a uniform size inside the mesh you can maybe try `hsiz` instead of `hmax` (it can be more efficient). Another possibility can be to install and enable scotch library (mesh renumbering to limit cache misses).
Best

**Comment by ttsesm** [comment]
Thanks @Algiane, I will try also to play with the `hsiz` parameters. 

Is there a link to a tutorial or something how to use mmg with scotch?

Thanks.

**Comment by Algiane** [comment]
Hi,

  - You can download and install scotch from this repository: https://gitlab.inria.fr/scotch/scotch. The last release of Mmg is compatible with version 5 and 6 of scotch but not the 7 one (so you probably want to download the last [6.1.3](https://gitlab.inria.fr/scotch/scotch/-/releases/v6.1.3) release).
 
  - For Mmg you need only scotch (so if you have trouble at compilation, you can disable other targets such as ptscotch or scotchmumps).

  -  Then, if you perform installation of scotch (`make install` command), Mmg will probably find automatically `scotch` and enable the `USE_SCOTCH` flag of `CMake`. In the other cases (scotch built but not installed or scotch not automatically founded) you can help Mmg by setting `SCOTCH_DIR` CMake valriable to scotch installation directory:
  `cmake -DSCOTCH_DIR=<my-path-to-scotch/scotch-v6.1.3> ...`
  
  Once Mmg is builded with scotch the mesh renumbering is automatically performed (if the mesh is large enough).

Regards,

**Comment by Algiane** [comment]
Hi @ttsesm , 

Can I close this issue ?

Thanks by advance,
Algiane

**Comment by ttsesm** [comment]
@Algiane sure, I will close it myself. For now I do not have something else. If I need anything comes up, I will update.

Thanks for the support ;-).
