### ISSUE TITLE
Preprocessor test of Scotch version fails with 5.1

### ISSUE THREAD

**Issue by davidjsherman** [MmgTools/mmg#14]
Scotch 5.1 defines a non-integer value for `SCOTCH_VERSION`, which will cause compilation of 
[common/librnbg.c](https://github.com/MmgTools/mmg/blame/a8ef84c4d6a65218addf360d0596bf26a376df61/src/common/librnbg.c#L55) to fail, because the C preprocessor cannot do floating point arithmetic.

The first of the five similar compilations errors is
```
In file included from src/common/librnbg.h:37:0,
                 from src/common/librnbg.c:38:
src/common/librnbg.c: In function '_MMG5_kPartBoxCompute':
/usr/include/scotch/scotch.h:63:24: error: floating constant in preprocessor expression
 #define SCOTCH_VERSION 5.1
                        ^
```

Since Scotch 5.1 is quite old, the dependency on a newer version of this optional package needs to be documented.

Unfortunately, 5.1 is the latest version of Scotch that is available in the Debian package archive, so a naive user will run into this error, unless the documentation says otherwise.

**Comment by Algiane** [comment]
Hello David,

Thank you for the bug report.

I think that the following patch must correct the compilations errors:
[SCOTCH_VERSION.txt](https://github.com/MmgTools/mmg/files/760428/SCOTCH_VERSION.txt)

Can you confirm that it works for you?

Best Regards,

Algiane

**Comment by davidjsherman** [comment]
Yes, this patch corrects compilation using a legacy Scotch version.
Thanks!
