### ISSUE TITLE
Compilation problem on Windows 10

### ISSUE THREAD

**Issue by gndelgad** [MmgTools/mmg#17]
Hi! I'm using Cygwin and I try to compile mmg3d in Windows following your instructions. Unfortunately when I do:

$make

I get the following sequence of errors concerning 'quad' and 'ptr':

Dans la fonction ‘MMG3D_Set_meshSize’:
/cygdrive/d/MMG/mmg-develop/src/mmg3d/API_functions_3d.c:173:12: erreur : ‘MMG5_Mesh {alias struct <anonymous>}’ has no member named ‘quad_t’
   if ( mesh->quad )
            ^
In file included from /cygdrive/d/MMG/mmg-develop/src/common/chrono.h:28:0,
                 from /cygdrive/d/MMG/mmg-develop/src/common/libmmgcommon.h:40,
                 from /cygdrive/d/MMG/mmg-develop/src/mmg3d/mmg3d.h:28,
                 from /cygdrive/d/MMG/mmg-develop/src/mmg3d/API_functions_3d.c:41:
/cygdrive/d/MMG/mmg-develop/src/mmg3d/API_functions_3d.c:174:28: erreur : ‘MMG5_Mesh {alias struct <anonymous>}’ has no member named ‘quad_t’
     _MMG5_DEL_MEM(mesh,mesh->quad,(mesh->nquad+1)*sizeof(MMG5_Quad));
                            ^
/cygdrive/d/MMG/mmg-develop/build/src/common/mmgcommon.h:176:10: note : in definition of macro ‘_MMG5_DEL_MEM’
     free(ptr);                                  \
          ^

Any ideas? Thank you very much!

**Comment by Algiane** [comment]
Hi,

Thank you for using Mmg.
I have corrected the bug by renaming the quad field of the mesh: it seems that using cygwin, the "sys/types.h" header file define a macro that rename the "quad" word into the "quad_t" one.

Regards,

Algiane

**Comment by gndelgad** [comment]
Great! Thank you

Regards,
Gabriel
