### ISSUE TITLE
required edges ignored

### ISSUE THREAD

**Issue by Mathias-Fuchs** [MmgTools/mmg#171]
Hello,
it seems required edges are being ignored in the most recent version, please see [https://forum.mmgtools.org/t/mmg-ignores-required-edges/671](url) for an example program. I didn't receive an answer there, so I'm trying to raise an issue here.
If that program calls the mmg API in a way it shouldn't, a warning should be printed.
M

**Comment by Algiane** [comment]
Hi @Mathias-Fuchs ,

I agree that the user input required edges have to be preserved if possible: the branch `feature/mmg2dls-missing-required-edges` should fix this issue. The only case where some required edges are not preserved is the case where the level-set function intersect them. 

Best Regards,
Algiane
