### ISSUE TITLE
How to run simple tests?

### ISSUE THREAD

**Issue by Trophime** [MmgTools/mmg#19]
Hi, 
I've tried to compile 5.23.5 with the following options:
```
 -DCMAKE_BUILD_TYPE=Release \
 -DUSE_SCOTCH=ON \
 -DLIBMMG3D_SHARED=ON \
 -DLIBMMG2D_SHARED=ON \
 -DLIBMMGS_SHARED=ON \
 -DBUILD_TESTING=ON \
 -DONLY_VERY_SHORT_TESTS=ON
```

Then I'd like to run the basic tests but I cannot figure out a way to do it?
Could you give me some hints how to run these tests?

Best

**Comment by Algiane** [comment]
Hi,

You can run the 3 basic tests (one per Mmg's app) with the ctest command (you need to launch it from your build directory):
```
cd mmg/build
ctest
```
I hope that it will helps.

Best Regards,

Algiane

**Comment by Algiane** [comment]
Hi,

You can run the 3 basic tests (one per Mmg's app) by running the ctest command from your build directory:
```
cd mmg/build
ctest
```

I hope that it will help.

Best Regards,

Algiane

**Comment by Trophime** [comment]
That's exactly what I've tried but I got this error message:
```
make[1]: Leaving directory '/build/mmg-5.2.5'
   debian/rules override_dh_auto_test
make[1]: Entering directory '/build/mmg-5.2.5'
echo "auto test"
auto test
cd /build/mmg-5.2.5/debian/build
ctest
*********************************
No test configuration file found!
*********************************
Usage

  ctest [options]

make[1]: Leaving directory '/build/mmg-5.2.5'
   create-stamp debian/debhelper-build-stamp
 fakeroot debian/rules binary
```

**Comment by Trophime** [comment]
my bad. ctest was actually not run in the proper directory during debian package build.
Now it's working as expected.
Sorry for the trouble

Best

**Comment by Algiane** [comment]
I'm glad that you find what happens.

Best Regards

**Comment by Trophime** [comment]
Is there a document that describes how to port mmg3D v4 based apps to mmg?
I would like to use the latest version in gmsh instead of the V4 version?
Is it possible to replace bamg by mmgs?

Thanks for any pointer

**Comment by Algiane** [comment]
Yes, you have an exemple in the **libexamples/mmg3d/adaptation_example1** directory:
The main.cold file corresponds to a call to the mmg3d-v4 library and the main.c file to the mmg v5 library.

If you want, I have a very beginning work that replace mmg3d v4 by mmg v5 in gmsh 2.13.2. Just say me if you are interested.

I think that bamg works only for 2D meshes, thus if you want to replace it, you'll need to use mmg2d (for 2D meshes) instead of mmgs (that is devoted to 3D surface meshes)

**Comment by Trophime** [comment]
It would be really nice if you can share with me your work on porting v5 to gmsh 2.13.2 :)

**Comment by Algiane** [comment]
I send you a patch by private email.
