### ISSUE TITLE
MMG2D_Get_triFromEdge

### ISSUE THREAD

**Issue by fgillet** [MmgTools/mmg#22]
Hello,

I have an issue with the function MMG2D_Get_triFromEdge.

The problem comes form the fact that the edges are not packed;
When I get the number of Edges form MMG2D_Get_meshSize, I only get the number of good edges (edges with first node index > 0): na

However MMG2D_Get_triFromEdge expect the "true" (i.e. not packed edge index);
So If I loop from 1 to na to get the edges and pass the index of the loop to MMG2D_Get_triFromEdge as the edge index I will not get the good parent if there is "false" edges in the list.

best regards,

fabien

**Comment by Algiane** [comment]
Hello Fabien,

Thank you for the bug report.

In the next release of Mmg2d, the boundary edges will be packed. Thus I have patch the problem but not in a very clean way: I haven't modified the **MMG2D_Get_triFromEdge** arguments but now, **ked** is ignored and the function will process the edges in order. Thus, to obtain the triangle to which belong the fifth edge, you must call 5 times the fonction **MMG2D_Get_triFromEdge**. I hope that it is enough for you usage...

 Can you please pull the master branch a say me if it works for you?

Best regards,

Algiane

**Comment by fgillet** [comment]
Perfect!

thanks,

Fabien
