### ISSUE TITLE
[mmg3D] MMG3D_Set_tetrahedron(...) with wrong orientation

### ISSUE THREAD

**Issue by mjuhoor** [MmgTools/mmg#23]
Hello,

There might be a bug when using the function
`MMG3D_Set_tetrahedron(MMG5_pMesh mesh, int v0, int v1, int v2, int v3, int ref, int pos)`
in file mmg3d/API_functions_3d.c, when input tetrahedron has wrong vertex ordering.

The condition `if ( vol <= _MMG5_EPSD2 )` line 506 checks if the determinant is negative or zero.
Thus, the `else if ( vol < 0.0 )` line 522 is never executed.

This means MMG will always say that the tetrahedron is a sliver or that all coordinates are zero. No reordering of nodes will occur.

**Comment by Algiane** [comment]
Hello,

Thank you for this bug report. It must be corrected in the 5.3.5 hotfix.

Best regards,

Algiane
