### ISSUE TITLE
[mmg3d] implicit domain meshing crashes if no edges

### ISSUE THREAD

**Issue by mxncr** [MmgTools/mmg#26]
Hello,

I am using mmg3d as a library. When I call `MMG3D_Set_iparameter(mesh, met, MG3D_IPARAM_iso, 1);` on a mesh without edges, there is a segmentation fault. The crash is due to a check on edges in  _MMG3D_skipIso(MMG5_pMesh mesh):

>    /* Skip edges with MG_ISO refs */
>   k = 1;
>   do {
>     pa = &mesh->edge[k];
>     if ( abs(pa->ref) != MG_ISO ) {
>       pa->ref = abs(pa->ref);
>       continue;
>     }
>     ....

As there is no edge in my mesh, `mesh->edge[1]` is undefined.

Is this a bug or meshes without edges should not be used ?

By the way, thanks for Mmg, this a great remeshing library !
Maxence

Stack trace:

> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff013640d in _MMG3D_skipIso (mesh=0x55555591c740) at /home/maxence/ext/mmg/src/mmg3d/API_functions_3d.c:1637
> 1637        if ( abs(pa->ref) != MG_ISO ) {
> (gdb)
> (gdb) bt
> #0  0x00007ffff013640d in _MMG3D_skipIso (mesh=0x55555591c740) at /home/maxence/ext/mmg/src/mmg3d/API_functions_3d.c:1637
> #1  0x00007ffff0136aaf in MMG3D_Set_iparameter (mesh=0x55555591c740, sol=0x55555590f3f0, iparam=4, val=1) at /home/maxence/ext/mmg/src/mmg3d/API_functions_3d.c:1723

**Comment by Algiane** [comment]
Hello Maxence,

Thank you for this bug report.

I think that it is corrected now (master branch) and that you can use a mesh without edges. Please let me know if it works on your test case and I will draft a new release.

Regards,

Algiane

**Comment by mxncr** [comment]
The last version on the master branch is now working on my test cases.
Thank you for the bug fix.

Maxence
