### ISSUE TITLE
Anisotropic adaptation : regression between commits 83358bbe and da75fd07d

### ISSUE THREAD

**Issue by Algiane** [MmgTools/mmg#34]
Regression on the anisotropic mesh produced on the [Kratos coarse sphere test case](https://github.com/KratosMultiphysics/Kratos/wiki/%5BUtilities%5D-MMG-Process#how-can-i-use-this-library).

<img width="1154" alt="capture d ecran 2019-02-06 14 01 21" src="https://user-images.githubusercontent.com/11232703/52343194-b32a0280-2a17-11e9-8aa6-574d3c64b3b4.png">

**Comment by loumalouomega** [comment]
Hi @Algiane the error is in our side?, I ask as the maintainer of the MMGProcess

**Comment by Algiane** [comment]
Hi @loumalouomega ,

No, it is on our side : 
- the first step of Mmg consists to remesh the surface mesh very fast using non-conformal patterns
- for anisotropic meshes, this step may creates spurious sharp angles (we are unable to check the angle between two adjacent surface triangles because the mesh is not conformal)
- thus, in the commit [da75fd07d](https://github.com/MmgTools/mmg/commit/da75fd07df80ce9c8e2747cf6d4209812f6ab227) I have removed this step in the anisotropic remeshing process
- starting from a coarse mesh, it leads to downgrade the final mesh

**Comment by loumalouomega** [comment]
OK, good to know

**Comment by Algiane** [comment]
Solved by multiple commits (from [49688f9](https://github.com/MmgTools/mmg/commit/49688f958ce3a2d04b2ffb3eccb6c99935098191) to [d736919](https://github.com/MmgTools/mmg/commit/d73691923b3c6dd0acfabbd4e9c081fcacb4c945)) : in aniso, call a conformal pattern step  that correspond to the isotropic non-conformal pattern step but that splits only 1 edge by tetra and that check the sharp angle creation.
