### ISSUE TITLE
The usage of -nsd when mesh generating

### ISSUE THREAD

**Issue by ZhuShentian** [MmgTools/mmg#37]
hi, i used the mmg2d_o3 tool by following the  tutorials page,but how to get the result below:

![image](https://user-images.githubusercontent.com/13469273/52995246-fdb67080-3454-11e9-9a98-9ff615901688.png)

i used the command line below:
mmg2d_O3.exe -ar 10 -hmax 10 -nsd 4 acdcBdy.mesh

i have tried some values of the -nsd parameter,but none of them could generate the correct result.
what is the correct usage of the -nsd?

**Comment by Algiane** [comment]
Hi,

using the _-nsd_ 4 option, did you get the following result? 
<img width="281" alt="capture d ecran 2019-02-25 12 01 25" src="https://user-images.githubusercontent.com/11232703/53333121-465aa780-38f5-11e9-8044-82a58abffcda.png">

If yes, this mesh correspond to the "inside" of the A letter (which is the subdomain of reference 4+1 when you save all the subdomains of the mesh). You can look [here](https://forum.mmgtools.org/t/keep-only-one-subdomain/227/5?u=algiane) for a more detailed explanation.

**Comment by ZhuShentian** [comment]
Yes,, so i can't get the result below by only one command line :(
anyway, thanks for your reply.
