### ISSUE TITLE
How to preserve some required vertices which don't constitute any triangles when using -optim?

### ISSUE THREAD

**Issue by ZhuShentian** [MmgTools/mmg#38]
Hi, I am using mmg2d  to improve the quality of my meshes. I set some required vertices, one of these required vertices is not the vertex  of any triangle. After running the command line below:
mmg2d.exe -optim  output.mesh

I found that the number of required vertices was 1 less than the initial mesh( 67->66,e.g),and in the 'Vertices' list, i couldn't find the vertex that mentioned above. How to avoid this happening?

**Comment by Algiane** [comment]
Hi,

It is not possible to preserve an isolated vertex using Mmg. 

- In library mode, the easier way to preserve your point is to not give it to Mmg and to renumber it after the Mmg call (your point will be the _np+1_ point, _np_ being the number of points returned by Mmg.

- In command line mode, if you want to have an automatic process, you can use a script that append your node to the mesh nodes and save a new mesh file.

I hope that it will helps.

Regards,
Algiane

**Comment by ZhuShentian** [comment]
Thanks. It helps a lot.
