### ISSUE TITLE
Error occurred when compiling ISCD Commons Library under W10-64bits

### ISSUE THREAD

**Issue by ZhuShentian** [MmgTools/mmg#39]
Hi, while compiling the  ISCD Commons Library using visual studio 2015,i got the error below:

“sys/time.h”: No such file or directory
“pthread.h”: No such file or directory

I'm wondering whether the  ISCD Commons Library is support windows platform.

**Comment by Algiane** [comment]
Hi,

You are right, the Commons library isn't supported on windows. I have pushed a modification inspired from Mmg for the sys/time.h error but I don't know how to use pthreads on windows (note that I am far from being a windows and/or pthread expert, I have only tried to use the  [http://sourceware.org/pthreads-win32/](http://sourceware.org/pthreads-win32/) library but I ended up with another missing header (time.h)).

I don't work on the Commons project so sorry to not have more time to give to this problems.

Regards,

Algiane
