### ISSUE TITLE
M_LIB?

### ISSUE THREAD

**Issue by ccoulet** [MmgTools/mmg#4]
Hi
I'm currently trying to compile mmgtools under W7-64bits with the latest version of CMake.
During the generation, I met an error:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
M_LIB (ADVANCED)
Could you give me some advise about this error?

Thanks in advance
Christophe

**Comment by Algiane** [comment]
Hi, 

in our project, the M_LIB variable of CMake refers to the Math.h C library.  It seems that the find_library(M_LIB m) don't works on windows. You can help CMake by specifying manually this variable (advanced mode). I hope this will help you.

For now, our applications are mainly developped under Linux and Mac Os X thus you may have some other troubles to build and run it under W7. I am not really used to use this OS but I will do my best to help you if you need it.

**Comment by ccoulet** [comment]
Thanks for your answer.
By manually adding the location of math.h library in CMake, the process ended without any other error.
I will continue my investigation...
