### ISSUE TITLE
Update calls to fread and fscan to inhibit ignoring return value warning

### ISSUE THREAD

**Issue by kayarre** [MmgTools/mmg#41]
Suggest replacing fread and fscan with an assert statement like `assert(fscan () > 0);` or `assert(fread() > 0)` in the instances where return values are ignored.

Is there anything wrong with that?

**Comment by Algiane** [comment]
Hi,

`assert` calls are removed in release build so we can't call functions inside but I can define a macro to check the return values of fread/fscan.

We are currently in ß-release and I don't want to add new things in the code before the release (except hotfixes for regressions), thus this check will be integrated in the following release (5.5).

Regards

**Comment by Algiane** [comment]
Hi,

I have released a version where the warnings have been removed so I close the discussion.

Regards
