### ISSUE TITLE
MMG2D_Set/Get_edge with negative reference gives unexpected results

### ISSUE THREAD

**Issue by pavanakumar** [MmgTools/mmg#48]
The edge reference in edge_Set function must be non-negative (> 0) for MMG2D to give correct references back using the edge_Get function after adaptation. Is this the expected behaviour or is this a bug?

**Comment by Algiane** [comment]
Hello,

Mmg uses negative references for debugging purposes (so developpers only must use negative refs). Thus it is not surprising to have unexpected behaviours using it.
I have recently added a very short documentation about this in the "prerequisite" section of the [Mmg tutorials](https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials), I will try to add this information in another place for a better indexing.

Regards,

Algiane
