### ISSUE TITLE
Trouble linking on Mac

### ISSUE THREAD

**Issue by updega2** [MmgTools/mmg#5]
Hi,

I'm am trying to build and link to your project. 

I am using Mac OSX 10.10, clang 7.0, and cmake 3.4. 

1. I build your libraries, and that works great.
2. I build my own static library containing code that calls and links to your libraries, and that works great.
3. I build an executable that links to my static library (from step 2) and your libraries, and get a linking error:

Undefined symbols for architecture x86_64:
  "MMGS_Init_mesh(MMG5_arg, ...)", referenced from:

I have done this with other libraries in the past and had no problem. There seems to be something weird going on. Any suggestions would help.

Thanks!

**Comment by Algiane** [comment]
Hi,
Maybe there is a problem in the order in which you link the libraries. I think that you need to link first your library, then mmg:
```
-lyour_lib -lmmg
```

Are your code and library written in C?
May I see the linking command line?

Regards, 

Algiane

**Comment by updega2** [comment]
Thanks for the reply!

I am using cmake, so I build my library in one directory, and then I build the executable in another directory. Then I use target_link_libraries for the executable. I link to my library first and then mmg. I actually tried both orders just in case, but got the same error.

My code is written in c++.

**Comment by Algiane** [comment]
I think that it is fixed now: we miss the extern "C" in header files. 
Let me know if you still have troubles.

Good evening.

**Comment by updega2** [comment]
Oh awesome, thanks for the help! I'll let you know if it works out.

**Comment by updega2** [comment]
It worked! Thanks again for the help :)
