### ISSUE TITLE
Problem in the execution on Windows of the develop branch code

### ISSUE THREAD

**Issue by CapucineLegentil** [MmgTools/mmg#56]
Hi!
When reading the .mesh file, the MMG_FSCANF function returns "Reading error". I tested the executable on Linux and everything works correctly. I do not know what is responsible for this bug, but I wanted to report it to you.
I hope this can be resolved.
Thanks

**Comment by Algiane** [comment]
Hi Capucine,

Thank you for this feedback.
I discover that MSVC doesn't expand the __VA_ARGS__ macro in the same way than GNU compilers. I have pushed a correction in the `develop` branch: now, for non POSIX runtime environment (like MSVC), we check only that the fscanf function returns a null or positive value.

I hope that it will work!

Regards,
Algiane
