### ISSUE TITLE
requirement for vertex and entities ids

### ISSUE THREAD

**Issue by prudhomm** [MmgTools/mmg#57]
@Algiane Is there a requirement that the ids of the vertices and entities built using MMG are contiguous(0..n-1 or 1...n) or not?  if yes should the ids start from 0 or 1?

it seems to be the case as we don't have the vertex id from `MMG3D_Get_vertex`, it seems to be defined implicitly.
```
for (int k = 0; k < nVertices; k++)                                                                                         
    {                                                                                                                           
        MMG3D_Get_vertex(mesh ...); // -> vertex id is k ( or k+1)?
    }
```
In our mesh data structures, the ids do not have to be contiguous (say 0...n-1), we use hash tables to store the vertices and entities with respect to the id key.

**Comment by Algiane** [comment]
Hello,

Within the Mmg data structure:
  1. The MMG3D_Get_vertex function assumes that the vertices indices are contiguous (which is true if you have called the MMG3D_mmg3dlib function before the MMG3D_Get_vertex one);

  2. The vertices numbering starts from 1 and ends at nVertices (included). I will add a word about that on the Setters documentation. It must be translucent when using Getters.

Regarding the MMG3D_Get_vertex API, it allows only to get the vertices in growing order of numbering (1->nVertices) but as you provide the memory adress to store the vertex coordinates, you can fill a non contiguous structure.

I suppose that your question comes from the fact that when filling your hash table, you want to acces the vertices in a random order?

Thank you by advance for your answer,

Regards,

**Comment by prudhomm** [comment]
@Algiane thanks, that's what I thought looking at the interface. I will need to remap the point/element ids.

Regarding the storage of the vertex, no problem as you said.

I am currently interfacing mmg (2D,3D and Surfacic) with feelpp (http://github.com/feelpp/feelpp) . Once done I will do that same with ParMmg which will become crucial for us for some application (as discussed by phone last year). I will let you know when we get working examples.

regarding the hash tables we do not require anything (eg contiguity) regarding the ids, we want fast access but the meshers (for example gmsh) we use may not produce continuous numbering. 
We find hash tables to be a good compromise from the performance and usability/flexibility  point of view

**Comment by prudhomm** [comment]
@Algiane in sequential things are going nice and we get our first results with remesh alone in feelpp see here feelpp/feelpp#1430. 
The objective now is to get parallel remeshing working in the context of ALE problems where moving the mesh yield bad meshes.
Is there (a) specific publication(s) to cite when using mmg/parmmg ?

**Comment by prudhomm** [comment]
is this the publication we should cite: _Three-dimensional adaptive domain remeshing, implicit domain meshing, and applications to free and moving boundary problems - C. Dapogny, C. Dobrzynski and P. Frey - April 1, 2014 - JCP_

**Comment by Algiane** [comment]
Hi,

I am glad that you have successfully interfaced Mmg in Feelpp!

Regarding the citations (and thank you for citing us!):
  - yes for Mmg;
  - we don't have publication on ParMmg for now but you can cite the following research report:
    [Parallel unstructured mesh adaptation using iterative remeshing and repartitioning ](https://hal.inria.fr/hal-02386837)

Regards,
Algiane
