### ISSUE TITLE
Add support for mmg as a subproject and use CMAKE_INSTALL_* vars

### ISSUE THREAD

**Issue by prudhomm** [MmgTools/mmg#58]
in feelpp we use mmg as a subproject, the necessary changes are minor. 
Also I would propose using modern cmake to install the targets.
Finally use GnuInstallDirs to define standard cmake install directories

**Comment by prudhomm** [comment]
@Algiane @lcirrott here is the result of the work with feelpp:
https://youtu.be/RD9xu4ONnvw (3D)
and
https://www.youtube.com/watch?v=U4pfn_Y0ZZ0 (2D)
2D and 3D moving object with ALE and remeshing once in a while when the mesh starts to have bad quality.
Next steps is to do that in parallel with parmmg.
thanks for your help !

**Comment by Algiane** [comment]
Great results!

Thank you for interfacing us ;-)
