### ISSUE TITLE
keeping some labeled elements or facets fixed

### ISSUE THREAD

**Issue by prudhomm** [MmgTools/mmg#62]
@Algiane is it possible to have some elements or facets marked as "fixed" such that mmg do not touch them? In our app, we would like to keep part of the domain( a body embedded into a domain) with the same mesh inside and on its boundary the same over the remeshing process. It is the outside which is remeshed to the movement of the body.

**Comment by prudhomm** [comment]
In other words I do not want the boundary of the body and its interior being remeshed

**Comment by prj-** [comment]
See [MMG3D_Set_requiredTriangle](https://github.com/MmgTools/mmg/blob/32770b48ebc659ef0b599f653c60b87d746e4378/src/mmg3d/libmmg3d.h#L631) and [MMG3D_Set_requiredTetrahedron](https://github.com/MmgTools/mmg/blob/32770b48ebc659ef0b599f653c60b87d746e4378/src/mmg3d/libmmg3d.h#L597).

**Comment by prudhomm** [comment]
thanks @prj- !!
