### ISSUE TITLE
MMG3D does not preserve references

### ISSUE THREAD

**Issue by pavanakumar** [MmgTools/mmg#71]
I am facing problems with MMG3D with preserving reference of vertices of parallelTriangles. I freeze the adaptation at these boundary triangles using MMG3D_Set_parallelTriangle. In order to match the frozen triangles with the unadapted mesh I add a integer reference. This reference is not being preserved even though the triangles are not modified.

But I never faced this issue in MMG2D Set_parallelEdge which does preserve the reference of the vertex after adaption. If the reference changes arbitrarily what is the purpose of having this in MMG3D?

**Comment by pavanakumar** [comment]
An update on the problem. Indeed MMG3D did not change the reference but is adding new ones in my case it is adding node reference "1". So I added an arbitrary offset say 256 to my integer reference and was able to recover my original integer references. So the question is how does MMG number the new references? Is there a logic to it?

**Comment by Algiane** [comment]
Hello Pavanakumar,

I am not sure to understand what is modified (and why). If I understand : 
  - you freeze some triangles using the MMG3D_Set_parallelTriangle function;
  - you add an integer reference to the nodes of the freezed area;
  - Mmg3d doesn't change the reference of the points of the freezed area;

Am I right?

If yes, normally, Mmg isn't allowed to insert new points in the freezed area so I suppose that the points of reference 1 are located outside this area?
Are they on the surface or inside the volume?
It will be very helpful if you can attach a small test case that reproduces the problem.

Regards,
Algiane

**Comment by pavanakumar** [comment]
I am working on the minimum 3D mesh and will post it soon. The one I have right now is not sharable.
