### ISSUE TITLE
ftbfs with gcc 10

### ISSUE THREAD

**Issue by xantares** [MmgTools/mmg#72]
it fails to build with gcc>=10 as now it default to -fno-common:
```
/usr/sbin/ld: CMakeFiles/libmmg_so.dir/src/mmg2d/anisosiz_2d.c.o:(.bss+0x30): multiple definition of `MMG5_renumbering'; CMakeFiles/libmmg_so.dir/src/common/mmgexterns.c.o:(.bss+0x0): first defined here
/usr/sbin/ld: CMakeFiles/libmmg_so.dir/src/mmg2d/anisosiz_2d.c.o:(.bss+0x38): multiple definition of `MMG5_compute_meanMetricAtMarkedPoints'; CMakeFiles/libmmg_so.dir/src/common/mmgexterns.c.o:(.bss+0x8): first defined here             
/usr/sbin/ld: CMakeFiles/libmmg_so.dir/src/mmg2d/anisosiz_2d.c.o:(.bss+0x40): multiple definition of `MMG5_grad2metreq_ani'; CMakeFiles/libmmg_so.dir/src/common/mmgexterns.c.o:(.bss+0x10): first defined here
...
```

**Comment by Algiane** [comment]
Hello @xantares and thank you for your feedback,

Your error is linked with the #61 pull request.

My main issue is that:
  - the compilation with gcc>=10 is ok if I merge this PR but it brokes the compilation with clang;
  - without any modification, the compilation works with clang and gcc<10 (or gcc>=10 with `-fcommon flag`);

I haven't succeed to conciliate the clang and gcc>=10 without adding compiler flags (but I recognize that I am not really confortable with the "multiple definition" errors) .

I will try to make a decision in the coming days (I will probably force a compiler flag).

Regards,
Algiane

**Comment by xantares** [comment]
I just tried #61 successfully on both gcc 10 & clang, without needing to set any compiler flags

**Comment by prj-** [comment]
It is not successful on macOS Catalina with clang.

**Comment by xantares** [comment]
why ? logs please

**Comment by prj-** [comment]
```
Scanning dependencies of target mmg3d
[ 76%] Building C object CMakeFiles/mmg3d.dir/src/mmg3d/mmg3d.c.o
[ 76%] Linking C executable bin/mmg3d_O3
Undefined symbols for architecture x86_64:
  "_MMG3D_PROctreein", referenced from:
      _MMG3D_setfunc in libmmg3d.a(libmmg3d_tools.c.o)
      _MMG5_boucle_for in libmmg3d.a(mmg3d1_delone.c.o)
     (maybe you meant: _MMG3D_PROctreein_ani, _MMG3D_PROctreein_iso )
  "_MMG3D_defsiz", referenced from:
      _MMG3D_setfunc in libmmg3d.a(libmmg3d_tools.c.o)
      _MMG5_mmg3d1_delone in libmmg3d.a(mmg3d1_delone.c.o)
      _MMG5_mmg3d1_pattern in libmmg3d.a(mmg3d1_pattern.c.o)
     (maybe you meant: _MMG3D_defsiz_ani, _MMG3D_defsiz_iso )
  "_MMG3D_gradsiz", referenced from:
      _MMG3D_setfunc in libmmg3d.a(libmmg3d_tools.c.o)
      _MMG5_mmg3d1_delone in libmmg3d.a(mmg3d1_delone.c.o)
      _MMG5_mmg3d1_pattern in libmmg3d.a(mmg3d1_pattern.c.o)
     (maybe you meant: _MMG3D_gradsiz_ani, _MMG3D_gradsiz_iso , _MMG3D_gradsizreq_iso , _MMG3D_gradsizreq_ani )
[...]
```

**Comment by Algiane** [comment]
Hi,

Thank you for your help @prj.

Forcing `-fcommon` flag make the compilation ok with (clang v11 + catalina) but I would like to understand what is the clean way to declare the function pointers so both compiler can build the project without adding any flag....

Best regards,

Algiane
