### ISSUE TITLE
narrow band

### ISSUE THREAD

**Issue by edljk** [MmgTools/mmg#82]
In the documentation, the following instructions mesh a 0 level set provided by the sampled function provided in the elephant.sol file

````mmg
mmg3d_O3 cube -sol elephant.sol -ls -nr -hausd 0.001 -hgrad 1.3 -hmax 0.05
````
Instead of using global parameters like hmin or hmax, is it possible in this level set case to add a metric vector (usually contained in a .sol file)?  Should this narrow band refining be generated in several steps?
Thanks!

**Comment by Algiane** [comment]
Hi Edouard,

This feature is not yet available in the released version of Mmg but can be tested if you checkout the 'develop' branch of the project.

In this case, you can provide your metric using the `-met` command line argument:
```
mmg3d_O3 cube -sol elephant.sol -met metric.sol -ls -nr -hausd 0.001 -hgrad 1.3 
```

Do not hesitate to get back to me if you have any troubles.

Regards, 
Algiane

**Comment by edljk** [comment]
Great, will have a look, thanks a lot!!
