### ISSUE TITLE
Specifying target triangle or vertex count for the result mesh

### ISSUE THREAD

**Issue by zizo007** [MmgTools/mmg#84]
Hi!

I was reading the docs looking for an option to specify the target polygon or vertex count in the result mesh.
I thought from the description of command line parameters that this can be obtained by using `hmin`, `hmax`, and `hsiz`:

```
-hmin   val  minimal mesh size
-hmax   val  maximal mesh size
-hsiz   val  constant mesh size
```

However, these paramters seem to not have any connection with this or maybe I just misunderstand something.
Is there any way to specify the exact target count or at least approximate it?

Thanks in advance.

**Comment by Algiane** [comment]
Hi,

I am sorry but Mmg doesn't allow to target a specific polygon or vertex count. We only provide control on the edge lengths.
A way to estimate the number of created tetrahedra may be to use the input metric to compute the future cell volume but it is not so simple as Mmg smooth internally this metric and as the surface mesh is controled by the Hausdorff distance.
You can find [here](https://forum.mmgtools.org/t/theory-behind-mmg-meshing-algorithm/285/4 ) a discussion about this kind of estimation.

I hope that it will help you,

Regards,
Algiane

**Comment by zizo007** [comment]
Thanks for the quick reply. I will read this related discussion.
