### ISSUE TITLE
MMG > 5.4.x seems to not work on WSL2 (with Ubuntu 20.04.1 image)

### ISSUE THREAD

**Issue by jenom** [MmgTools/mmg#87]
Hello,

when I try to call the Linux binary 5.5.1 in the WSL on windows I get 
```
$ ./mmg3d_O3
-bash: ./mmg3d_O3: No such file or directory
```
whereas version 5.4.3 works without problems. 
Looking at the two version with ldd and file I get for **5.5.1**
```
$ ldd mmg3d_O3
        linux-vdso.so.1 (0x00007ffc836ab000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff96927f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff969263000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff969258000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff969109000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff968f28000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff968f0b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff968d19000)
        /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007ff9692b3000)

$ file mmg3d_O3
mmg3d_O3: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
``` 
and for **5.4.3**
```
$ ldd mmg3d_O3
        linux-vdso.so.1 (0x00007fff4dba9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc405bc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc403ca000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efc4071c000)

$ file mmg3d_O3
mmg3d_O3: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=1050287f1bab015ac5ef259ebd08c29d61dc2f1c, not stripped
```
I really have no idea what's going on as ldd seems to find everything and the architecture seems to be correct as well (a common cause for the initial error message). WSL 2 works as a VM and `uname -a` gives `Linux $(NAME) 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Finally, compiling 5.5.1 inside WSL, ldd returns
```
        linux-vdso.so.1 (0x00007ffdd3040000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff19097a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff190788000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff190be9000)
```

I appreciate any input/ideas.

Best,
Johannes

**Comment by lcirrottola** [comment]
Hello,
Thank you for the feedback. It seems that the additional dependencies that you have listed for v5.5.1 are not found on your system, causing the executable to crash. It is possible that slightly different compilation flags were used for creating the binaries for the two releases, causing these differences in the dependencies.

I am not an expert of WSL, but I can only suggest to look for those libraries in your system, to install them if missing, and to create a symbolic link to them in the location where the executable expects to find them.
It could be worth it to try with the latest v5.5.2, although it is possible that you experience the very same problem.

If the problem persists, anyway, it is good news that the compilation on your image works.

Best,
Luca

**Comment by jenom** [comment]
Thanks a lot the help. I tried version 5.5.2 and it runs fine without a problem in WSL so I guess the problem doesn't persist.
