### ISSUE TITLE
Different behaviours across versions

### ISSUE THREAD

**Issue by lberti** [MmgTools/mmg#91]
Hello!

I am testing MMG remeshing features via the FEEL++ project, and creating unit tests. Feel++ uses the develop branch of MMG.
I have the impression that the same code produces different results according to the MMG version I use. 

1) With the version 5.4.2, if no remeshing metric is specified, I get this error both in 2d and 3d `MMG5_scale_scalarMetric: at least 1 wrong metric`; with the current version (5.5.2), this error/check seem to have disappeared in 3d, and this produces a segfault later in the execution (the previous error stopped MMG in the ANALYSIS step).

2) In a unit square/cube [0,1]^d, d=2,3, I remesh iteratively, changing the metric among the following metrics
h*{"(abs(x)+1):x", "x*x:x", "exp(x):x", "(x*x+y*y+1): x : y"}, with h fixed, up to 20 times in total. With the version 5.4.2 the process is smooth and fast, meaning that the resulting meshes are very similar to each other, and remeshing essentially boils down to the addition/subtraction of some vertices and edges. With version 5.5.2, after a first round across all the metrics, the refinement associated to the exponential becomes very fine and the two results differ.

If you needed any further specifications, I can provide them.
Thank you!

**Comment by lcirrottola** [comment]
Hello,
I will try to reproduce myself problem 2 and come back to you. Can you please share the meshes you use to reproduce problem 1?

Thanks,
Luca

**Comment by lcirrottola** [comment]
Hello,
If this problem is still alive, in order to reproduce it we would need some information about the mesh producing problem 1, and some explanation about the metrics for problem 2 (I don't know how to interpret the syntax: h*{"(abs(x)+1):x", "xx:x", "exp(x):x", "(xx+y*y+1): x : y"}).

Thanks,
Luca

**Comment by lberti** [comment]
Hi. I'm sorry, I've solved it. I would propose to close/delete this question.

**Comment by lcirrottola** [comment]
No problem! :-)
