### ISSUE TITLE
Surface mesh refinement 

### ISSUE THREAD

**Issue by pareshspatel** [MmgTools/mmg#96]
Is it possible to split and swap edges in mmgs? Goal is to split long edges without collapsing any edges. 

Would following check (like noswap and nomove) in mmgs1.c do?  

if ( !mesh->info.nocollapse ) {
      nc = adpcol(mesh,met);
      if ( nc < 0 ) {
        fprintf(stderr,"\n  ## Unable to complete mesh. Exit program.\n");
        return 0;
      }
}

Thanks!

**Comment by lcirrottola** [comment]
Hello,
By default there is no parameter to do it, but you should indeed be able to implement a `nocollapse` functionality  as you outlined, by wrapping the call to the `adpcol` function in a conditional statement, and by doing the same also with the call to the `colelt`function (always in mmgs1.c).

Let me know if it works.
Yours,
Luca

**Comment by pareshspatel** [comment]
Thank you!
