### ISSUE TITLE
impose different -hausd for different parts of a mesh

### ISSUE THREAD

**Issue by yfzhou42** [MmgTools/mmg#97]
In the documentation for -hausd it reads "Note that you can impose different Hausdorff numbers over different boundary componants using a parameter file." however the link for "parameter file" does not exist. Can someone elaborate on this parameter file (how to construct, how to use)? For example I have a mesh with multimaterials and want to set the contact boundary with a different -hausd from the rest. Can I do that and how?

**Comment by lcirrottola** [comment]
Hello,
On the website there is an example of parameter file with a short explanation of how to build it:
https://www.mmgtools.org/parameter-file
(basically, it assigns different parameters to part of boundaries with different references).

Hope it helps.
Yours,
Luca
